version: '2.2'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://es-master-node-01:9200
      ELASTICSEARCH_HOSTS: http://es-master-node-01:9200
    ports:
      - 5601:5601
    networks:
      - elastic-search_elastic

networks:
  elastic-search_elastic:
    external: true