heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls: ["https://www.dailytask.co"]
  service.name: dailytask 
  id: dailytask
  name: dailytask

output.elasticsearch:
  hosts: ["https://es01:9200", "https://es02:9200"]
  username: "elastic"
  password: "test"
  ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca/ca.crt"]

setup.kibana:
  host: "localhost:5601"
