#========================== Filebeat autodiscover ==============================
# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true
filebeat.inputs:
- type: docker
  containers.ids: 
    - '74ba4b6ef7bfb128cb16d9044cf3aca6f54799f588a3dee6635e63e4629ac6f3'
#========================== logstash output ===============================
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  worker: 1
#============================== Dashboards =====================================
setup.dashboards:
  enabled: false

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:5601"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
#============================== template setting =========================================
setup.template.overwrite: true
setup.template.settings:
  index:
    number_of_shards: 1
    codec: best_compression
    number_of_replicas: 0
