version: '2.2'

services:
  es-master-node:
    container_name: es-master-node-01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - node.name=es-master-node-01
      - node.master=true
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      - node.ml=false
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master-node-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic: